// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHM9fxnMAn5knnk1OP8sTyMyEeRmbD8iw',
    appId: '1:224935111699:web:14967ed20463d82ec223e6',
    messagingSenderId: '224935111699',
    projectId: 'connectplus-a75fb',
    authDomain: 'connectplus-a75fb.firebaseapp.com',
    storageBucket: 'connectplus-a75fb.appspot.com',
    measurementId: 'G-SP6Z478FS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDacCNNeLc8p-8N0CY5sz2TcbAR-ZHz3oI',
    appId: '1:224935111699:android:91472123aad85ed8c223e6',
    messagingSenderId: '224935111699',
    projectId: 'connectplus-a75fb',
    storageBucket: 'connectplus-a75fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPCNRxOJioTsOi50zGxiKlz37rTUAQLrU',
    appId: '1:224935111699:ios:d0b36121e0fc4f95c223e6',
    messagingSenderId: '224935111699',
    projectId: 'connectplus-a75fb',
    storageBucket: 'connectplus-a75fb.appspot.com',
    iosClientId: '224935111699-uchuisamuur9vq84ovni7261ai4av0sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.erasmusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPCNRxOJioTsOi50zGxiKlz37rTUAQLrU',
    appId: '1:224935111699:ios:ded0dfda5b839611c223e6',
    messagingSenderId: '224935111699',
    projectId: 'connectplus-a75fb',
    storageBucket: 'connectplus-a75fb.appspot.com',
    iosClientId: '224935111699-rp8b3henvqfrqfc0ikjfans3fgq81mfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.erasmusConnect.RunnerTests',
  );
}
