name: erasmus_connect
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  chat_gpt_sdk: 2.0.2
  path_drawing: ^1.0.0
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.4
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.1.2
  animations: ^2.0.7

  # figma:
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  pin_code_fields: ^7.3.0
  intl: ^0.18.0
  scroll_snap_list: ^0.9.1
  url_launcher: ^6.1.11
  intl_phone_field: ^3.2.0
  searchfield: ^0.8.3
  image_picker: ^1.0.0
  flip_card: ^0.7.0
  carousel_slider: ^4.2.1
  firebase_database: ^10.2.3
  video_thumbnail: ^0.5.3
  path_provider: ^2.0.15
  image: ^4.0.17
  firebase_storage: ^11.2.4
  firebase_crashlytics: ^3.3.3
  file_picker: ^5.3.2
  geolocator: ^9.0.2
  card_swiper: ^2.0.4
  image_card: ^0.0.4
  geocoding: ^2.1.0
  http: ^0.13.6
  like_button: ^2.0.5
  flutter_hooks: ^0.18.6
  google_maps_flutter: ^2.3.1
  flutter_local_notifications: ^15.1.0+1
  dropdown_search: ^5.0.6
  firebase_messaging: ^14.6.4
  awesome_notifications: ^0.6.19
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^10.4.3
  jitsi_meet_wrapper: ^0.2.0+1
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/connect_plus_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/connect_plus_logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/UrbanistRomanBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/UrbanistRomanThin.ttf
          weight: 100
        - asset: assets/fonts/UrbanistRomanSemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300
    - family: Intern
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
